namespace: tp7-kustomize
images:
  - name: spring-petclinic
    newTag: 4.0.0-SNAPSHOT
resources:
  - "../base"

patches:
  - path: replicas.yaml
    target:
      kind: Deployment
      name: clinic-deploy
  - path: patch-routing.yaml
